-- MySQL Script generated by MySQL Workbench
-- Mon Nov 10 16:00:55 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inua
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inua` ;

-- -----------------------------------------------------
-- Schema inua
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inua` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `inua` ;

-- -----------------------------------------------------
-- Table `inua`.`Factories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inua`.`Factories` ;

CREATE TABLE IF NOT EXISTS `inua`.`Factories` (
  `idFactories` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Description` VARCHAR(1000) NULL,
  PRIMARY KEY (`idFactories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inua`.`UserRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inua`.`UserRoles` ;

CREATE TABLE IF NOT EXISTS `inua`.`UserRoles` (
  `idUserRoles` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUserRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inua`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inua`.`Users` ;

CREATE TABLE IF NOT EXISTS `inua`.`Users` (
  `idUsers` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `idFactories` INT NOT NULL,
  `Password` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `idUserRoles` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `idFactories`),
  INDEX `fk_Users_Factories1_idx` (`idFactories` ASC),
  INDEX `fk_Users_UserRoles1_idx` (`idUserRoles` ASC),
  CONSTRAINT `fk_Users_Factories1`
    FOREIGN KEY (`idFactories`)
    REFERENCES `inua`.`Factories` (`idFactories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_UserRoles1`
    FOREIGN KEY (`idUserRoles`)
    REFERENCES `inua`.`UserRoles` (`idUserRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inua`.`FactoryTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inua`.`FactoryTypes` ;

CREATE TABLE IF NOT EXISTS `inua`.`FactoryTypes` (
  `idFactoryTypes` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idFactoryTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inua`.`Factories_has_FactoryTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inua`.`Factories_has_FactoryTypes` ;

CREATE TABLE IF NOT EXISTS `inua`.`Factories_has_FactoryTypes` (
  `idFactories` INT NOT NULL,
  `idFactoryTypes` INT NOT NULL,
  PRIMARY KEY (`idFactories`, `idFactoryTypes`),
  INDEX `fk_Factories_has_FactoryTypes_FactoryTypes1_idx` (`idFactoryTypes` ASC),
  INDEX `fk_Factories_has_FactoryTypes_Factories_idx` (`idFactories` ASC),
  CONSTRAINT `fk_Factories_has_FactoryTypes_Factories`
    FOREIGN KEY (`idFactories`)
    REFERENCES `inua`.`Factories` (`idFactories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factories_has_FactoryTypes_FactoryTypes1`
    FOREIGN KEY (`idFactoryTypes`)
    REFERENCES `inua`.`FactoryTypes` (`idFactoryTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inua`.`Branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inua`.`Branches` ;

CREATE TABLE IF NOT EXISTS `inua`.`Branches` (
  `idBranches` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `idFactories` INT NOT NULL,
  PRIMARY KEY (`idBranches`),
  INDEX `fk_Branches_Factories1_idx` (`idFactories` ASC),
  CONSTRAINT `fk_Branches_Factories1`
    FOREIGN KEY (`idFactories`)
    REFERENCES `inua`.`Factories` (`idFactories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
